application: ruscheduler
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /css/images
  static_dir: css/images
- url: /images
  static_dir: images

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest
- name: jinja2
  version: latest